// <auto-generated />
using System;
using AdsSqlApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AdsSqlApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260814185139_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("AdsSqlApi.Domain.Entities.Pads", b =>
            {
                b.Property<Guid>("Id");
                b.Property<DateTime>("CreatedAtUtc");
                b.Property<bool>("IsActive");
                b.Property<string>("Code").IsRequired().HasMaxLength(50);
                b.Property<string>("Name").IsRequired().HasMaxLength(200);
                b.HasKey("Id");
                b.ToTable("Pads");
            });

            modelBuilder.Entity("AdsSqlApi.Domain.Entities.Well", b =>
            {
                b.Property<Guid>("Id");
                b.Property<DateTime>("CreatedAtUtc");
                b.Property<bool>("IsActive");
                b.Property<string>("Code").IsRequired().HasMaxLength(50);
                b.Property<string>("Name").IsRequired().HasMaxLength(200);
                b.HasKey("Id");
                b.ToTable("Wells");
            });
        }
    }
}
